package br.com.senac.view;

import br.com.senac.model.RegistroVenda;
import br.com.senac.model.Usuario;
import br.com.senac.persistence.RegistroDAO;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class TelaListaVendas extends javax.swing.JFrame {

    private Usuario usuarioAutenticado;
    private RegistroDAO registroDAO;
    private DefaultTableModel tableModel;
    
    public TelaListaVendas(Usuario usuarioAutenticado) {
        this.usuarioAutenticado = usuarioAutenticado;
        this.registroDAO = new RegistroDAO();
        initComponents();
        permissoes(usuarioAutenticado);
        configurarTabela();
        carregarDados();
        
        addWindowListener(new WindowAdapter (){
            @Override
            public void windowClosing(WindowEvent e){
                int opcao = JOptionPane.showConfirmDialog(null, "Deseja voltar para o menu principal?", "Voltar", JOptionPane.YES_NO_OPTION);
                
                if (opcao == JOptionPane.YES_OPTION){
                    MenuPrincipal menuPrincipal = new MenuPrincipal(usuarioAutenticado);
                    menuPrincipal.setVisible(true);
                    dispose();
                }
            }
        });
    }
    
    private void permissoes(Usuario usuarioAutenticado) {
        switch (usuarioAutenticado.getTipoUsuario()) {
            case "Securitário":
                btnEditarRegistro.setEnabled(false);
                btnRemoverRegistro.setEnabled(false);
                break;
            case "Gerente":
                btnEditarRegistro.setEnabled(true);
                btnRemoverRegistro.setEnabled(true);
                break;
        }
    }
    
    private void configurarTabela() {
        tableModel = new DefaultTableModel(
            new String[]{"Cliente", "CPF do Cliente", "Data da Venda", "Tipo de Seguro", "Valor da Apólice", "Fiel?"}, 0);
        jTable1.setModel(tableModel);
    }
    
    private void carregarDados() {
        List<RegistroVenda> registros = registroDAO.listar();
        tableModel.setRowCount(0);

        for (RegistroVenda registro : registros) {
            tableModel.addRow(new Object[]{
                registro.getNomeCliente(),
                registro.getCpfCliente(),
                registro.getDataVenda(),
                registro.getTipoSeguro(),
                registro.getValorApolice(),
                registro.isFiel() ? "Sim" : "Não"
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnVoltar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnEditarRegistro = new javax.swing.JButton();
        btnRemoverRegistro = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("Lista de Vendas");

        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        btnEditarRegistro.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnEditarRegistro.setText("Editar Registro");
        btnEditarRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarRegistroActionPerformed(evt);
            }
        });

        btnRemoverRegistro.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnRemoverRegistro.setText("Remover Registro");
        btnRemoverRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverRegistroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(83, 83, 83)
                .addComponent(btnVoltar)
                .addGap(20, 20, 20))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(btnEditarRegistro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addComponent(btnRemoverRegistro)
                .addGap(60, 60, 60))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(btnVoltar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEditarRegistro)
                    .addComponent(btnRemoverRegistro))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 400));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditarRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarRegistroActionPerformed
        int linhaSelecionada = jTable1.getSelectedRow();
        
        if(linhaSelecionada == -1){
            JOptionPane.showMessageDialog(this, "Selecione um registro para editar.", "Atenção", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        List<RegistroVenda> registros = registroDAO.listar();
        RegistroVenda registroSelecionado = registros.get(linhaSelecionada);
        
        TelaRegistro telaRegistro = new TelaRegistro(usuarioAutenticado, registroSelecionado);
        telaRegistro.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnEditarRegistroActionPerformed

    private void btnRemoverRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverRegistroActionPerformed
        int linhaSelecionada = jTable1.getSelectedRow();
        
        if (linhaSelecionada == -1) {
            JOptionPane.showMessageDialog(this, "Selecione um registro para remover.", "Atenção", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        int confirmacao = JOptionPane.showConfirmDialog(this, "Tem certeza que deseja remover este registro?", "Confirmação", JOptionPane.YES_NO_OPTION);
        if(confirmacao == JOptionPane.YES_OPTION){
           List<RegistroVenda> registros = registroDAO.listar();
           RegistroVenda registroSelecionado = registros.get(linhaSelecionada);
           registroDAO.excluir(registroSelecionado.getId());
           
           carregarDados();
           JOptionPane.showMessageDialog(this, "Registro removido com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnRemoverRegistroActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        int opcao = JOptionPane.showConfirmDialog(null, "Deseja voltar para o menu principal", "Voltar", JOptionPane.YES_NO_OPTION);
        if (opcao == JOptionPane.YES_OPTION){
            MenuPrincipal menuPrincipal = new MenuPrincipal(usuarioAutenticado);
            menuPrincipal.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_btnVoltarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditarRegistro;
    private javax.swing.JButton btnRemoverRegistro;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
