package br.com.senac.view;

import br.com.senac.model.PlanoFidelidade;
import br.com.senac.model.RegistroVenda;
import br.com.senac.model.Usuario;
import br.com.senac.persistence.RegistroDAO;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

public class TelaRegistro extends javax.swing.JFrame {

    private RegistroDAO registroDAO;
    private Usuario usuarioAutenticado;
    private RegistroVenda registroEdicao;
    private boolean modoEdicao;
    
    public TelaRegistro(Usuario usuarioAutenticado) {
        this.usuarioAutenticado = usuarioAutenticado;
        this.registroDAO = new RegistroDAO();
        this.modoEdicao = false;
        initComponents();
        
        addWindowListener(new WindowAdapter (){
            @Override
            public void windowClosing(WindowEvent e){
                int opcao = JOptionPane.showConfirmDialog(null, "Deseja voltar para o menu principal?", "Voltar", JOptionPane.YES_NO_OPTION);
                
                if (opcao == JOptionPane.YES_OPTION){
                    MenuPrincipal menuPrincipal = new MenuPrincipal(usuarioAutenticado);
                    menuPrincipal.setVisible(true);
                    dispose();
                }
            }
        });
    }
    
    public TelaRegistro(Usuario usuarioAutenticado, RegistroVenda registroEdicao){
        this.usuarioAutenticado = usuarioAutenticado;
        this.registroEdicao = registroEdicao;
        this.registroDAO = new RegistroDAO();
        this.modoEdicao = true;
        initComponents();
        preencherCampos();
        
        addWindowListener(new WindowAdapter (){
            @Override
            public void windowClosing(WindowEvent e){
                int opcao = JOptionPane.showConfirmDialog(null, "Deseja voltar para o menu principal?", "Voltar", JOptionPane.YES_NO_OPTION);
                
                if (opcao == JOptionPane.YES_OPTION){
                    MenuPrincipal menuPrincipal = new MenuPrincipal(usuarioAutenticado);
                    menuPrincipal.setVisible(true);
                    dispose();
                }
            }
        });
    }
    
    private void preencherCampos(){
        if (registroEdicao != null) {
            txtNomeCliente.setText(registroEdicao.getNomeCliente());
            txtCPF.setText(registroEdicao.getCpfCliente());
            txtDataVenda.setText(new SimpleDateFormat("dd/MM/yyyy").format(registroEdicao.getDataVenda()));
            cbxTipoSeguro.setSelectedItem(registroEdicao.getTipoSeguro());
            txtValorApolice.setText(String.valueOf(registroEdicao.getValorApolice()));
            if (registroEdicao.isFiel()) {
                rbtnSim.setSelected(true);
            } 
            else {
                rbtnNao.setSelected(true);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rbtngFiel = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNomeCliente = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtCPF = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        txtDataVenda = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        cbxTipoSeguro = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        txtValorApolice = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        rbtnSim = new javax.swing.JRadioButton();
        rbtnNao = new javax.swing.JRadioButton();
        btnRegistrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("Registro de Venda");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setText("Nome do Cliente:");

        txtNomeCliente.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setText("CPF do Cliente:");

        try {
            txtCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCPF.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel4.setText("Data da Venda:");

        txtDataVenda.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));
        txtDataVenda.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel5.setText("Tipo de Seguro:");

        cbxTipoSeguro.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        cbxTipoSeguro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Carro", "Casa", "Vida" }));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel6.setText("Valor da Apólice:");

        txtValorApolice.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel7.setText("Cliente Fiel?");

        rbtngFiel.add(rbtnSim);
        rbtnSim.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        rbtnSim.setText("Sim");

        rbtngFiel.add(rbtnNao);
        rbtnNao.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        rbtnNao.setText("Não");

        btnRegistrar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(rbtnSim)
                                .addGap(45, 45, 45)
                                .addComponent(rbtnNao)
                                .addGap(161, 161, 161)
                                .addComponent(btnRegistrar))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel7)
                                        .addComponent(jLabel6)))
                                .addGap(38, 38, 38)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtNomeCliente, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCPF, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                                    .addComponent(txtDataVenda, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbxTipoSeguro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtValorApolice, javax.swing.GroupLayout.Alignment.LEADING))))))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtDataVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cbxTipoSeguro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtValorApolice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rbtnNao)
                            .addComponent(rbtnSim))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRegistrar)
                        .addGap(37, 37, 37))))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 450));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        String nomeCliente = txtNomeCliente.getText().trim();
        String cpfCliente = txtCPF.getText().trim();
        String tipoSeguro = (String) cbxTipoSeguro.getSelectedItem();
        String dataVendaStr = txtDataVenda.getText().trim();
        String valorApoliceStr = txtValorApolice.getText().trim();
        boolean fiel = rbtnSim.isSelected();
        
        StringBuilder erros = new StringBuilder();
        if (nomeCliente.isEmpty()) erros.append("- Nome do cliente\n");
        if (cpfCliente.isEmpty()) erros.append("- CPF do cliente\n");
        if (dataVendaStr.isEmpty()) erros.append("- Data da venda\n");
        if (valorApoliceStr.isEmpty()) erros.append("- Valor da apólice\n");
        if (!rbtnSim.isSelected() && !rbtnNao.isSelected()) erros.append("- Cliente é fiel?");
        
        if (erros.length() > 0){
            JOptionPane.showMessageDialog(this, "Os seguintes campos não podem estar vazios:\n" + erros.toString(), "Atenção", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        double valorApolice;
        try {
            valorApolice = Double.parseDouble(valorApoliceStr);
            if (valorApolice <= 0){
                JOptionPane.showMessageDialog(this, "O valor da apólice deve ser maior que zero.", "Atenção", JOptionPane.WARNING_MESSAGE);
                return;
            }
        }
        catch (NumberFormatException e){
            JOptionPane.showMessageDialog(this, "Valor da apólice inválido. Insira um número válido.", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        valorApolice = PlanoFidelidade.calcularValorComDesconto(tipoSeguro, valorApolice, fiel);
        
        java.util.Date dataVendaUtil = null;
        try {
            SimpleDateFormat formatoEntrada = new SimpleDateFormat("dd/MM/yyyy");
            dataVendaUtil = formatoEntrada.parse(dataVendaStr);
        }
        catch (Exception e){
            JOptionPane.showMessageDialog(null, "Data inválida. Use o formato DD/MM/YYYY.", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        java.sql.Date dataVendaSql = new java.sql.Date(dataVendaUtil.getTime());
        
        RegistroVenda registro = new RegistroVenda();
        registro.setNomeCliente(nomeCliente);
        registro.setCpfCliente(cpfCliente);
        registro.setTipoSeguro(tipoSeguro);
        registro.setDataVenda(dataVendaSql);
        registro.setValorApolice(valorApolice);
        registro.setFiel(fiel);
        
        if (modoEdicao) {
        registro.setId(registroEdicao.getId());
        registroDAO.atualizar(registro);
        JOptionPane.showMessageDialog(this, "Registro atualizado com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
        } 
        else {
        registroDAO.adicionar(registro);
        JOptionPane.showMessageDialog(this, "Registro salvo com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
        }
        
        txtNomeCliente.setText("");
        txtCPF.setText("");
        txtDataVenda.setText("");
        txtValorApolice.setText("");
        rbtnSim.setSelected(false);
        rbtnNao.setSelected(false);
    }//GEN-LAST:event_btnRegistrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JComboBox<String> cbxTipoSeguro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton rbtnNao;
    private javax.swing.JRadioButton rbtnSim;
    private javax.swing.ButtonGroup rbtngFiel;
    private javax.swing.JFormattedTextField txtCPF;
    private javax.swing.JFormattedTextField txtDataVenda;
    private javax.swing.JTextField txtNomeCliente;
    private javax.swing.JTextField txtValorApolice;
    // End of variables declaration//GEN-END:variables
}
